; Auto-generated. Do not edit!


(cl:in-package agv-msg)


;//! \htmlinclude targetFeedback.msg.html

(cl:defclass <targetFeedback> (roslisp-msg-protocol:ros-message)
  ((progress
    :reader progress
    :initarg :progress
    :type std_msgs-msg:String
    :initform (cl:make-instance 'std_msgs-msg:String)))
)

(cl:defclass targetFeedback (<targetFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <targetFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'targetFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name agv-msg:<targetFeedback> is deprecated: use agv-msg:targetFeedback instead.")))

(cl:ensure-generic-function 'progress-val :lambda-list '(m))
(cl:defmethod progress-val ((m <targetFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader agv-msg:progress-val is deprecated.  Use agv-msg:progress instead.")
  (progress m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <targetFeedback>) ostream)
  "Serializes a message object of type '<targetFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'progress) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <targetFeedback>) istream)
  "Deserializes a message object of type '<targetFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'progress) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<targetFeedback>)))
  "Returns string type for a message object of type '<targetFeedback>"
  "agv/targetFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'targetFeedback)))
  "Returns string type for a message object of type 'targetFeedback"
  "agv/targetFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<targetFeedback>)))
  "Returns md5sum for a message object of type '<targetFeedback>"
  "84c8ded4cc051789ccfd80bf9239d5e9")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'targetFeedback)))
  "Returns md5sum for a message object of type 'targetFeedback"
  "84c8ded4cc051789ccfd80bf9239d5e9")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<targetFeedback>)))
  "Returns full string definition for message of type '<targetFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%std_msgs/String progress~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'targetFeedback)))
  "Returns full string definition for message of type 'targetFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%std_msgs/String progress~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <targetFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'progress))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <targetFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'targetFeedback
    (cl:cons ':progress (progress msg))
))
