; Auto-generated. Do not edit!


(cl:in-package agv-msg)


;//! \htmlinclude targetResult.msg.html

(cl:defclass <targetResult> (roslisp-msg-protocol:ros-message)
  ((info
    :reader info
    :initarg :info
    :type std_msgs-msg:String
    :initform (cl:make-instance 'std_msgs-msg:String)))
)

(cl:defclass targetResult (<targetResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <targetResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'targetResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name agv-msg:<targetResult> is deprecated: use agv-msg:targetResult instead.")))

(cl:ensure-generic-function 'info-val :lambda-list '(m))
(cl:defmethod info-val ((m <targetResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader agv-msg:info-val is deprecated.  Use agv-msg:info instead.")
  (info m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <targetResult>) ostream)
  "Serializes a message object of type '<targetResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'info) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <targetResult>) istream)
  "Deserializes a message object of type '<targetResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'info) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<targetResult>)))
  "Returns string type for a message object of type '<targetResult>"
  "agv/targetResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'targetResult)))
  "Returns string type for a message object of type 'targetResult"
  "agv/targetResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<targetResult>)))
  "Returns md5sum for a message object of type '<targetResult>"
  "12a155e3803bd9637acdd5f5509da193")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'targetResult)))
  "Returns md5sum for a message object of type 'targetResult"
  "12a155e3803bd9637acdd5f5509da193")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<targetResult>)))
  "Returns full string definition for message of type '<targetResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%std_msgs/String info~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'targetResult)))
  "Returns full string definition for message of type 'targetResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%std_msgs/String info~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <targetResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'info))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <targetResult>))
  "Converts a ROS message object to a list"
  (cl:list 'targetResult
    (cl:cons ':info (info msg))
))
