; Auto-generated. Do not edit!


(cl:in-package agv-msg)


;//! \htmlinclude targetGoal.msg.html

(cl:defclass <targetGoal> (roslisp-msg-protocol:ros-message)
  ((trigger
    :reader trigger
    :initarg :trigger
    :type std_msgs-msg:String
    :initform (cl:make-instance 'std_msgs-msg:String)))
)

(cl:defclass targetGoal (<targetGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <targetGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'targetGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name agv-msg:<targetGoal> is deprecated: use agv-msg:targetGoal instead.")))

(cl:ensure-generic-function 'trigger-val :lambda-list '(m))
(cl:defmethod trigger-val ((m <targetGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader agv-msg:trigger-val is deprecated.  Use agv-msg:trigger instead.")
  (trigger m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <targetGoal>) ostream)
  "Serializes a message object of type '<targetGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'trigger) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <targetGoal>) istream)
  "Deserializes a message object of type '<targetGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'trigger) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<targetGoal>)))
  "Returns string type for a message object of type '<targetGoal>"
  "agv/targetGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'targetGoal)))
  "Returns string type for a message object of type 'targetGoal"
  "agv/targetGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<targetGoal>)))
  "Returns md5sum for a message object of type '<targetGoal>"
  "907835fb5709cf0857fb8d8ecc0edf29")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'targetGoal)))
  "Returns md5sum for a message object of type 'targetGoal"
  "907835fb5709cf0857fb8d8ecc0edf29")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<targetGoal>)))
  "Returns full string definition for message of type '<targetGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%std_msgs/String trigger~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'targetGoal)))
  "Returns full string definition for message of type 'targetGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%std_msgs/String trigger~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <targetGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'trigger))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <targetGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'targetGoal
    (cl:cons ':trigger (trigger msg))
))
