// Auto-generated. Do not edit!

// (in-package agv.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let std_msgs = _finder('std_msgs');

//-----------------------------------------------------------

class targetFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.progress = null;
    }
    else {
      if (initObj.hasOwnProperty('progress')) {
        this.progress = initObj.progress
      }
      else {
        this.progress = new std_msgs.msg.String();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type targetFeedback
    // Serialize message field [progress]
    bufferOffset = std_msgs.msg.String.serialize(obj.progress, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type targetFeedback
    let len;
    let data = new targetFeedback(null);
    // Deserialize message field [progress]
    data.progress = std_msgs.msg.String.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += std_msgs.msg.String.getMessageSize(object.progress);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'agv/targetFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '84c8ded4cc051789ccfd80bf9239d5e9';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    std_msgs/String progress
    
    ================================================================================
    MSG: std_msgs/String
    string data
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new targetFeedback(null);
    if (msg.progress !== undefined) {
      resolved.progress = std_msgs.msg.String.Resolve(msg.progress)
    }
    else {
      resolved.progress = new std_msgs.msg.String()
    }

    return resolved;
    }
};

module.exports = targetFeedback;
