// Auto-generated. Do not edit!

// (in-package agv.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let std_msgs = _finder('std_msgs');

//-----------------------------------------------------------

class targetGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.trigger = null;
    }
    else {
      if (initObj.hasOwnProperty('trigger')) {
        this.trigger = initObj.trigger
      }
      else {
        this.trigger = new std_msgs.msg.String();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type targetGoal
    // Serialize message field [trigger]
    bufferOffset = std_msgs.msg.String.serialize(obj.trigger, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type targetGoal
    let len;
    let data = new targetGoal(null);
    // Deserialize message field [trigger]
    data.trigger = std_msgs.msg.String.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += std_msgs.msg.String.getMessageSize(object.trigger);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'agv/targetGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '907835fb5709cf0857fb8d8ecc0edf29';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    std_msgs/String trigger
    
    ================================================================================
    MSG: std_msgs/String
    string data
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new targetGoal(null);
    if (msg.trigger !== undefined) {
      resolved.trigger = std_msgs.msg.String.Resolve(msg.trigger)
    }
    else {
      resolved.trigger = new std_msgs.msg.String()
    }

    return resolved;
    }
};

module.exports = targetGoal;
