// Generated by gencpp from file agv/targetResult.msg
// DO NOT EDIT!


#ifndef AGV_MESSAGE_TARGETRESULT_H
#define AGV_MESSAGE_TARGETRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace agv
{
template <class ContainerAllocator>
struct targetResult_
{
  typedef targetResult_<ContainerAllocator> Type;

  targetResult_()
    : info()  {
    }
  targetResult_(const ContainerAllocator& _alloc)
    : info(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _info_type;
  _info_type info;





  typedef boost::shared_ptr< ::agv::targetResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv::targetResult_<ContainerAllocator> const> ConstPtr;

}; // struct targetResult_

typedef ::agv::targetResult_<std::allocator<void> > targetResult;

typedef boost::shared_ptr< ::agv::targetResult > targetResultPtr;
typedef boost::shared_ptr< ::agv::targetResult const> targetResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv::targetResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv::targetResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace agv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'agv': ['/home/zer0/AGV_ws/devel/share/agv/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::agv::targetResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv::targetResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv::targetResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv::targetResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv::targetResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv::targetResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv::targetResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "12a155e3803bd9637acdd5f5509da193";
  }

  static const char* value(const ::agv::targetResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x12a155e3803bd963ULL;
  static const uint64_t static_value2 = 0x7acdd5f5509da193ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv::targetResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv/targetResult";
  }

  static const char* value(const ::agv::targetResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv::targetResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
std_msgs/String info\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::agv::targetResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv::targetResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct targetResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv::targetResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv::targetResult_<ContainerAllocator>& v)
  {
    s << indent << "info: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MESSAGE_TARGETRESULT_H
