// Generated by gencpp from file agv/targetGoal.msg
// DO NOT EDIT!


#ifndef AGV_MESSAGE_TARGETGOAL_H
#define AGV_MESSAGE_TARGETGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace agv
{
template <class ContainerAllocator>
struct targetGoal_
{
  typedef targetGoal_<ContainerAllocator> Type;

  targetGoal_()
    : trigger()  {
    }
  targetGoal_(const ContainerAllocator& _alloc)
    : trigger(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _trigger_type;
  _trigger_type trigger;





  typedef boost::shared_ptr< ::agv::targetGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv::targetGoal_<ContainerAllocator> const> ConstPtr;

}; // struct targetGoal_

typedef ::agv::targetGoal_<std::allocator<void> > targetGoal;

typedef boost::shared_ptr< ::agv::targetGoal > targetGoalPtr;
typedef boost::shared_ptr< ::agv::targetGoal const> targetGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv::targetGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv::targetGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace agv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'agv': ['/home/zer0/AGV_ws/devel/share/agv/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::agv::targetGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv::targetGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv::targetGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv::targetGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv::targetGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv::targetGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv::targetGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "907835fb5709cf0857fb8d8ecc0edf29";
  }

  static const char* value(const ::agv::targetGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x907835fb5709cf08ULL;
  static const uint64_t static_value2 = 0x57fb8d8ecc0edf29ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv::targetGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv/targetGoal";
  }

  static const char* value(const ::agv::targetGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv::targetGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
std_msgs/String trigger\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::agv::targetGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv::targetGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.trigger);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct targetGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv::targetGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv::targetGoal_<ContainerAllocator>& v)
  {
    s << indent << "trigger: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.trigger);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MESSAGE_TARGETGOAL_H
